version: "1.0"
info:
  model: int-scaffold
packages:
- name: SE_BS_TestProject
  gitServerName: SE_BS_Test2Project
  gitUrl: https://github.com/BjornSkanberg1/SE_BS_TestProject
  gitUsername: BjornSkanberg1
  gitBranch: main
